spring:
  application:
    name: "myeurekaserver"
  config:
    import: "configserver:http://localhost:8071/"

# Actuator configuration:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:  # need readiness and liveness to ensure application is ready in docker compose to start other services
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true