build:
  version: "1.0"

loans:
  message: "Welcome to Bank loans related Default profile APIs from config server"
  contactDetails:
    name: "prijwalDefaultInstance"
    email: "prijwaldefaultinstace@bank.com"
  onCallSupport:
    - (+91) 1234-5678
    - (+91) 1234-5678
