spring:
  application:
    name: "mygatewayserver"
  config:
#    import: "optional:configserver:http://localhost:8071/"
    import: "configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery: # telling to connect with discovery server (eureka) and locate all the details for individuals microservices
        locator:
          enabled: false
          lowerCaseServiceId: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway: true
  info:
    env:
      enabled: true




build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts related Default profile APIs "
  contactDetails:
    name: "prijwalDefaultInstance"
    email: "prijwaldefaultinstace@bank.com"
  onCallSupport:
    - (+91) 1234-5678
    - (+91) 1234-5678

#Netflix eureka configurations

info:
  app:
    name: "mygatewayserver"
    description: "Bank gateway server Application"
    version: "1.0.0"
