build:
  version: "3.0"

loans:
  message: "Welcome to Bank loans related Prod profile APIs from config server"
  contactDetails:
    name: "prijwalProdInstance"
    email: "prijwalprodinstace@bank.com"
  onCallSupport:
    - (+91) 1234-5678
    - (+91) 1234-5678




