build:
  version: "3.0"

accounts:
  message: "Welcome to Bank loans related Prod profile APIs "
  contactDetails:
    name: "prijwalProdInstance"
    email: "prijwalprodinstace@bank.com"
  onCallSupport:
    - (+91) 1234-5678
    - (+91) 1234-5678
